### ISSUE TITLE
iRangeX Support :)

### ISSUE THREAD

**Issue by JulianGoesPro** [xythobuz/SerialGamepad#2]
Hey, I just stumbled over your awesome work! I got the iRangeX USB thing which plugs into a Receiver and strangely shows up "movement" in "USB Overdrive" but your prog doesn't list it under the devices, just my iPad/iPhone/Bluetooth, how can that be :)

http://www.banggood.com/IRangeX-FPV-Wireless-Simulator-For-PWM-PPM-S_BUS-DSM2-Receiver-p-1083772.html?rmmds=myorder

<img width="327" alt="screen shot 2016-10-16 at 16 54 41" src="https://cloud.githubusercontent.com/assets/11023597/19418392/3e5aa9f6-93c3-11e6-90b7-22fc9a20f78b.png">
<img width="668" alt="screen shot 2016-10-16 at 16 53 48" src="https://cloud.githubusercontent.com/assets/11023597/19418394/3e937e52-93c3-11e6-9f25-3e93bf3ccb06.png">
<img width="668" alt="screen shot 2016-10-16 at 16 07 21" src="https://cloud.githubusercontent.com/assets/11023597/19418393/3e823ca0-93c3-11e6-9f8f-2e77d8e1c08c.png">

in Overdrive moving the sticks, it will jump to the corresponding "threshold" so it sees 4ch
X is Throttle
Y is Roll
Z is Elevator
Ry is YAW

Would be cool if you could give me some thoughts on my problem, thank you very much!

**Comment by xythobuz** [comment]
I'm not sure what that's supposed to do with SerialGamepad. SerialGamepad emulates a USB Joystick, but the iRangeX already _is_ a USB Joystick. You don't need another one. And it doesn't show up in SerialGamepad because SerialGamepad lists all the available serial ports, which your device isn't.

As you say, iRangeX should _just work_, out of the box, without any drivers and certainly without SerialGamepad.

**Comment by JulianGoesPro** [comment]
Oh thanks for the explanation, wasn't aware of that^^ Guess the problem is at a different front :)

**Comment by xythobuz** [comment]
I don't think you need USB Overdrive or any other software for this to work. Just select the right USB Gamepad in your simulator and properly assign and calibrate your different channels.

USB Overdrive can be used to emulate keyboard macros and stuff like that with a USB Gamepad. I don't think that's what you want, and having it installed may cause the gamepad to not work in simulators (or any other game).

**Comment by JulianGoesPro** [comment]
Thanks, it wasn't working so I installed Overdrive but makes sense that it might even mess it more up (had hoped it kind of adds a driver or something as well)... will deinstall it and try some other game then LiftOff, thanks :)
