### ISSUE TITLE
wont work-controller not recognized

### ISSUE THREAD

**Issue by sajiv123** [xythobuz/SerialGamepad#3]
i cant get the controller to work trying to use this for fpv freerider

**Comment by xythobuz** [comment]
Well you need to give some more info... When you start SerialGamepad and open the serial port, do you see the movement of your sticks in the green bars in the SerialGamepad window? If so, the problem is probably with [foohid](https://github.com/unbit/foohid). Have you tried their latest version?

**Comment by xythobuz** [comment]
Please try again. I have updated the code to work with the most current foohid and it now also works on my system again... 😄
